=== Atomicwallet/lisk-sdk/protocol-specs/schema/lisk_protocol_specs.schema.json
{
	"title": "LiskProtocolSpec",
	"description": "Schema specification for JSON specs output",
	"$id": "https://lisk.io/schemas/protocol_specs",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"additionalProperties": false,
	"required": ["title", "summary", "runner", "handler", "testCases"],
	"properties": {
		"title": {
			"type": "string",
			"description": "A string type value giving a short title of the spec",
			"minLength": 10,
			"maxLength": 100
		},
		"summary": {
			"type": "string",
			"description": "A string type value explaining in detail purpose and value of the spec",
			"minLength": 25,
			"maxLength": 300
		},
		"runner": {
			"type": "string",
			"description": "A string identifier to point to a protocol spec name e.g. dpos, bft",
			"minLength": 3,
			"maxLength": 100,
			"pattern": "[a-z0-9_]*"
		},
		"handler": {
			"type": "string",
			"description": "A string value to differentiate between same identifier for protocol spec",
			"minLength": 3,
			"maxLength": 100,
			"pattern": "[a-z0-9_]*"
		},
		"config": {
			"$ref": "#/definitions/Config"
		},
		"testCases": {
			"type": "array",
			"description": "List down all test cases for current handler and runner",
			"items": {
				"$ref": "#/definitions/TestCase"
			}
		}
	},
	"definitions": {
		"Account": {
			"title": "Account",
			"description": "Schema to specify and validate account in JSON specs",
			"type": "object",
			"properties": {
				"address": {
					"type": "string"
				},
				"publicKey": {
					"type": "string"
				},
				"secondPublicKey": {
					"type": ["string", "null"]
				},
				"username": {
					"type": ["string", "null"]
				},
				"isDelegate": {
					"type": "boolean"
				},
				"secondSignature": {
					"type": "boolean"
				},
				"nameExist": {
					"type": "boolean"
				},
				"balance": {
					"type": ["string", "integer"]
				},
				"multiMin": {
					"type": "integer"
				},
				"multiLifetime": {
					"type": "integer"
				},
				"missedBlocks": {
					"type": "integer"
				},
				"producedBlocks": {
					"type": "integer"
				},
				"rank": {
					"type": ["integer", "null"]
				},
				"fees": {
					"type": "integer"
				},
				"rewards": {
					"type": "integer"
				},
				"vote": {
					"type": ["string", "integer"]
				},
				"productivity": {
					"type": "integer"
				}
			},
			"required": ["address", "publicKey", "isDelegate", "balance"]
		},
		"Block": {
			"title": "Block",
			"description": "Schema to specify and validate blocks in JSON specs",
			"type": "object",
			"properties": {
				"id": {
					"type": "string",
					"format": "id",
					"minLength": 1,
					"maxLength": 20
				},
				"height": {
					"type": "integer"
				},
				"blockSignature": {
					"type": "string",
					"format": "signature"
				},
				"generatorPublicKey": {
					"type": "string",
					"format": "publicKey"
				},
				"numberOfTransactions": {
					"type": "integer"
				},
				"payloadHash": {
					"type": "string",
					"format": "hex"
				},
				"payloadLength": {
					"type": "integer"
				},
				"previousBlockId": {
					"type": "string",
					"format": "id",
					"minLength": 1,
					"maxLength": 20
				},
				"timestamp": {
					"type": "integer"
				},
				"totalAmount": {
					"typeof": "string",
					"format": "amount"
				},
				"totalFee": {
					"typeof": "string",
					"format": "amount"
				},
				"reward": {
					"typeof": "string",
					"format": "amount"
				},
				"transactions": {
					"type": "array",
					"uniqueItems": true
				},
				"version": {
					"type": "integer",
					"minimum": 0
				}
			},
			"required": [
				"blockSignature",
				"generatorPublicKey",
				"numberOfTransactions",
				"payloadHash",
				"payloadLength",
				"timestamp",
				"totalAmount",
				"totalFee",
				"reward",
				"transactions",
				"version"
			]
		},
		"ChainState": {
			"title": "ChainState",
			"description": "A JSON object represents basic chain state for individual spec to be executed.",
			"type": "object",
			"properties": {
				"chain": {
					"type": "array",
					"uniqueItems": true,
					"items": {
						"$ref": "#/definitions/Block"
					}
				},
				"accounts": {
					"type": "array",
					"uniqueItems": true,
					"items": {
						"$ref": "#/definitions/Account"
					}
				}
			}
		},
		"Config": {
			"title": "Config",
			"description": "A JSON object containing all necessary configurations for the environment in which these specs were generated and individual test case can be verified.",
			"type": "object",
			"additionalProperties": true,
			"required": [],
			"properties": {
				"initialState": {
					"$ref": "#/definitions/ChainState"
				}
			}
		},
		"TestCase": {
			"title": "Schema for a single test case",
			"type": "object",
			"additionalProperties": false,
			"required": ["input", "output", "description"],
			"properties": {
				"description": {
					"type": "string",
					"minLength": 10,
					"maxLength": 300
				},
				"config": {
					"description": "Configuration for a single test case",
					"$ref": "#/definitions/Config"
				},
				"input": {
					"type": "object",
					"description": "Input must be specified as a single object. If its complex scenario, it should be divided to multiple to have simple input/output expectations.",
					"minProperties": 1
				},
				"output": {
					"type": "object",
					"description": "Output must be specified as a single object. If its complex scenario, it should be divided to multiple to have simple input/output expectations.",
					"required": [],
					"additionalProperties": true,
					"minProperties": 1,
					"properties": {
						"mutatedState": {
							"description": "Modified chain state",
							"$ref": "#/definitions/ChainState"
						}
					}
				}
			}
		}
	}
}

=== Atomicwallet/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/validBooleanEncodings.json
{
	"title": "Valid boolean encodings",
	"summary": "Examples of encoding booleans as required by lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "validBooleanEncodings",
	"testCases": [
		{
			"description": "Encoding of boolean types",
			"config": {
				"network": "devnet"
			},
			"input": {
				"booleanTrue": {
					"object": {
						"state": true
					},
					"schema": {
						"$id": "object",
						"type": "object",
						"properties": {
							"state": {
								"dataType": "boolean",
								"fieldNumber": 1
							}
						}
					}
				},
				"booleanFalse": {
					"object": {
						"state": false
					},
					"schema": {
						"$id": "object",
						"type": "object",
						"properties": {
							"state": {
								"dataType": "boolean",
								"fieldNumber": 1
							}
						}
					}
				}
			},
			"output": {
				"booleanTrue": "0801",
				"booleanFalse": "0800"
			}
		}
	]
}

=== Atomicwallet/lisk-sdk/protocol-specs/generator_outputs/transaction_network_id_and_change_order/multi_signature_transaction_validate.json
{
	"title": "Valid multi signature transaction",
	"summary": "A valid multi signature transaction",
	"config": {
		"network": "devnet"
	},
	"runner": "transaction_network_id_and_change_order",
	"handler": "multi_signature_transaction_validate",
	"testCases": [
		{
			"description": "A valid multi signature transaction",
			"input": {
				"account": {
					"passphrase": "wear protect skill sentence lift enter wild sting lottery power floor neglect",
					"privateKey": "8f41ff1e75c4f0f8a71bae4952266928d0e91660fc513566ac694fed61157497efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"publicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"address": "2129300327344985743L"
				},
				"networkIdentifier": "e48feb88db5b5cf5ad71d93cdcd1d879b6d5ed187a36b0002cc34e0ef9883255",
				"coSigners": [
					{
						"passphrase": "inherit moon normal relief spring bargain hobby join baby flash fog blood",
						"privateKey": "de4a28610239ceac2ec3f592e36a2ead8ed4ac93cb16aa0d996ab6bb0249da2c0b211fce4b615083701cb8a8c99407e464b2f9aa4f367095322de1b77e5fcfbe",
						"publicKey": "0b211fce4b615083701cb8a8c99407e464b2f9aa4f367095322de1b77e5fcfbe",
						"address": "18141291412139607230L"
					},
					{
						"passphrase": "better across runway mansion jar route valid crack panic favorite smooth sword",
						"privateKey": "de1520f8589408e76a97643ba7d27f20009b06899816c8af20f9b03f4a4bd8a66766ce280eb99e45d2cc7d9c8c852720940dab5d69f480e80477a97b4255d5d8",
						"publicKey": "6766ce280eb99e45d2cc7d9c8c852720940dab5d69f480e80477a97b4255d5d8",
						"address": "13191770412077040757L"
					},
					{
						"passphrase": "mirror swap middle hunt angle furnace maid scheme amazing box bachelor debris",
						"privateKey": "ad7462eb8f682b0c3424213ead044381ba0007bb65ce26287fc308027c871d951387d8ec6306807ffd6fe27ea3443985765c1157928bb09904307956f46a9972",
						"publicKey": "1387d8ec6306807ffd6fe27ea3443985765c1157928bb09904307956f46a9972",
						"address": "2443122499609067441L"
					}
				],
				"transaction": {
					"type": 12,
					"senderPublicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"nonce": "2",
					"fee": "100000000",
					"asset": {
						"min": 2,
						"lifetime": 22,
						"keysgroup": [
							"+0b211fce4b615083701cb8a8c99407e464b2f9aa4f367095322de1b77e5fcfbe",
							"+6766ce280eb99e45d2cc7d9c8c852720940dab5d69f480e80477a97b4255d5d8",
							"+1387d8ec6306807ffd6fe27ea3443985765c1157928bb09904307956f46a9972"
						]
					}
				}
			},
			"output": {
				"type": 12,
				"senderPublicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
				"nonce": "2",
				"fee": "100000000",
				"asset": {
					"min": 2,
					"lifetime": 22,
					"keysgroup": [
						"+0b211fce4b615083701cb8a8c99407e464b2f9aa4f367095322de1b77e5fcfbe",
						"+6766ce280eb99e45d2cc7d9c8c852720940dab5d69f480e80477a97b4255d5d8",
						"+1387d8ec6306807ffd6fe27ea3443985765c1157928bb09904307956f46a9972"
					]
				},
				"signature": "86df61f70592776be33928592cd54b7c2a557b402e1b60ff8598e9c8247d0df4a23483cdbef95be38f70128012212193ac6ba092f6dab07c8a5fb850fee8d109",
				"signatures": [
					"d1aec7c58d38825e6f5fea0a6d7a52539894d76a923e06c3d960d251ef144561af15e3568ac8adf1f250c3a5c8c76ad33a91f89c00c17dfcbfb35f4be5066d0c",
					"3d85e3ad5aa4627b145ed086a24b010dd5eb7011556e81aa5e4ddee99950bef5bd65f9b2f9edbe4fe8513b3520d606fc7d92c3b940acb27e1d75ab3e1ff5010a",
					"bb8571ad017d17ee24fde3c79e2a49d9a3ec1507e0333939a2d32d4251cd07a43397dc5c76d5f33c57e39963b4f967d7af792fd2ce811b150f2da1e9bfb85b03"
				],
				"id": "16380453991724472426"
			}
		}
	]
}

=== Atomicwallet/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/validEncodings.json
{
	"title": "Encondings for types supported by lisk-codec",
	"summary": "Examples of encoding all the types supported by lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "validEncodings",
	"testCases": [
		{
			"description": "Encoding 32 bit unsigned number",
			"input": {
				"object": {
					"number": 10
				},
				"schema": {
					"$id": "object1",
					"type": "object",
					"properties": {
						"number": {
							"dataType": "uint32",
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "080a"
			}
		},
		{
			"description": "Encoding 32 bit signed number",
			"input": {
				"object": {
					"number": -10
				},
				"schema": {
					"$id": "object2",
					"type": "object",
					"properties": {
						"number": {
							"dataType": "sint32",
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "0813"
			}
		},
		{
			"description": "Encoding 64 bit unsigned number",
			"input": {
				"object": {
					"number": 372036854775807
				},
				"schema": {
					"$id": "object3",
					"type": "object",
					"properties": {
						"number": {
							"dataType": "uint64",
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "08ffffc9a4d9cb54"
			}
		},
		{
			"description": "Encoding 64 bit signed number",
			"input": {
				"object": {
					"number": -9007199254740991
				},
				"schema": {
					"$id": "object4",
					"type": "object",
					"properties": {
						"number": {
							"dataType": "sint64",
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "08fdffffffffffff1f"
			}
		},
		{
			"description": "Encoding of boolean with value true",
			"input": {
				"object": {
					"state": true
				},
				"schema": {
					"$id": "object5",
					"type": "object",
					"properties": {
						"state": {
							"dataType": "boolean",
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "0801"
			}
		},
		{
			"description": "Encoding of boolean with value false",
			"input": {
				"object": {
					"state": false
				},
				"schema": {
					"$id": "object6",
					"type": "object",
					"properties": {
						"state": {
							"dataType": "boolean",
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "0800"
			}
		},
		{
			"description": "Encoding of string",
			"input": {
				"object": {
					"data": "Checkout Lisk SDK!"
				},
				"schema": {
					"$id": "object7",
					"type": "object",
					"properties": {
						"data": {
							"dataType": "string",
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "0a12436865636b6f7574204c69736b2053444b21"
			}
		},
		{
			"description": "Encoding of empty string",
			"input": {
				"object": {
					"data": ""
				},
				"schema": {
					"$id": "object8",
					"type": "object",
					"properties": {
						"data": {
							"dataType": "string",
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "0a00"
			}
		},
		{
			"description": "Encoding of chunk of bytes",
			"input": {
				"object": {
					"address": {
						"type": "Buffer",
						"data": [
							225,
							26,
							17,
							54,
							71,
							56,
							34,
							88,
							19,
							248,
							110,
							168,
							82,
							20,
							64,
							14,
							93,
							176,
							141,
							110
						]
					}
				},
				"schema": {
					"$id": "object9",
					"type": "object",
					"properties": {
						"address": {
							"dataType": "bytes",
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "0a14e11a11364738225813f86ea85214400e5db08d6e"
			}
		},
		{
			"description": "Encoding of empty bytes",
			"input": {
				"object": {
					"address": {
						"type": "Buffer",
						"data": []
					}
				},
				"schema": {
					"$id": "object10",
					"type": "object",
					"properties": {
						"address": {
							"dataType": "bytes",
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "0a00"
			}
		},
		{
			"description": "Encoding of object",
			"input": {
				"object": {
					"address": {
						"type": "Buffer",
						"data": [
							225,
							26,
							17,
							54,
							71,
							56,
							34,
							88,
							19,
							248,
							110,
							168,
							82,
							20,
							64,
							14,
							93,
							176,
							141,
							110
						]
					},
					"balance": 10000000,
					"isDelegate": true,
					"name": "delegate",
					"asset": {
						"data": "Check out the Lisk SDK now in binary!"
					}
				},
				"schema": {
					"$id": "object11",
					"type": "object",
					"properties": {
						"address": {
							"dataType": "bytes",
							"fieldNumber": 1
						},
						"balance": {
							"dataType": "uint64",
							"fieldNumber": 2
						},
						"isDelegate": {
							"dataType": "boolean",
							"fieldNumber": 3
						},
						"name": {
							"dataType": "string",
							"fieldNumber": 4
						},
						"asset": {
							"type": "object",
							"fieldNumber": 5,
							"properties": {
								"data": {
									"dataType": "string",
									"fieldNumber": 1
								}
							}
						}
					}
				}
			},
			"output": {
				"value": "0a14e11a11364738225813f86ea85214400e5db08d6e1080ade2041801220864656c65676174652a270a25436865636b206f757420746865204c69736b2053444b206e6f7720696e2062696e61727921"
			}
		},
		{
			"description": "Encoding of object with optional property",
			"input": {
				"object": {
					"isActive": true,
					"value": 1
				},
				"schema": {
					"$id": "object12",
					"type": "object",
					"properties": {
						"isActive": {
							"dataType": "boolean",
							"fieldNumber": 1
						},
						"data": {
							"dataType": "bytes",
							"fieldNumber": 2
						},
						"value": {
							"dataType": "uint64",
							"fieldNumber": 3
						}
					}
				}
			},
			"output": {
				"value": "08011801"
			}
		},
		{
			"description": "Encoding of integers array",
			"input": {
				"object": {
					"list": [3, 1, 4, 1, 5, 9, 2, 6, 5]
				},
				"schema": {
					"type": "object",
					"$id": "arrayUint32",
					"properties": {
						"list": {
							"type": "array",
							"items": {
								"dataType": "uint32"
							},
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "0a09030104010509020605"
			}
		},
		{
			"description": "Encoding of booleans array",
			"input": {
				"object": {
					"list": [true, true, false, true, false, false]
				},
				"schema": {
					"type": "object",
					"$id": "arrayBoolean",
					"properties": {
						"list": {
							"type": "array",
							"items": {
								"dataType": "boolean"
							},
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "0a06010100010000"
			}
		},
		{
			"description": "Encoding of strings array",
			"input": {
				"object": {
					"list": ["lisk", "", "gogogog"]
				},
				"schema": {
					"type": "object",
					"properties": {
						"list": {
							"type": "array",
							"items": {
								"dataType": "string"
							},
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "0a046c69736b0a000a07676f676f676f67"
			}
		},
		{
			"description": "Encoding of objects array",
			"input": {
				"object": {
					"myArray": [
						{
							"address": "e11a11364738225813f86ea85214400e5db08d6e",
							"amount": 100000
						},
						{
							"address": "aa2a11364738225813f86ea85214400e5db08fff",
							"amount": 300000
						}
					]
				},
				"schema": {
					"$id": "arrayObject",
					"type": "object",
					"properties": {
						"myArray": {
							"type": "array",
							"fieldNumber": 1,
							"items": {
								"type": "object",
								"properties": {
									"address": {
										"dataType": "string",
										"fieldNumber": 1
									},
									"amount": {
										"dataType": "uint64",
										"fieldNumber": 2
									}
								}
							}
						}
					}
				}
			},
			"output": {
				"value": "0a2e0a286531316131313336343733383232353831336638366561383532313434303065356462303864366510a08d060a2e0a286161326131313336343733383232353831336638366561383532313434303065356462303866666610e0a712"
			}
		},
		{
			"description": "Encoding of empty array",
			"input": {
				"object": {
					"list": []
				},
				"schema": {
					"type": "object",
					"$id": "emptyArray",
					"properties": {
						"list": {
							"type": "array",
							"items": {
								"dataType": "uint32"
							},
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": ""
			}
		}
	]
}

=== Atomicwallet/lisk-sdk/protocol-specs/generator_outputs/transaction_network_id_and_change_order/transfer_transaction_with_second_signature_validate.json
{
	"title": "Valid transfer transaction with second signature",
	"summary": "A valid transfer transaction with second signature",
	"config": {
		"network": "devnet"
	},
	"runner": "transaction_network_id_and_change_order",
	"handler": "transfer_transaction_with_second_signature_validate",
	"testCases": [
		{
			"description": "A valid transfer transaction with second signature",
			"input": {
				"account": {
					"passphrase": "wear protect skill sentence lift enter wild sting lottery power floor neglect",
					"privateKey": "8f41ff1e75c4f0f8a71bae4952266928d0e91660fc513566ac694fed61157497efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"publicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"address": "2129300327344985743L"
				},
				"secondPassphrase": "inherit moon normal relief spring bargain hobby join baby flash fog blood",
				"networkIdentifier": "e48feb88db5b5cf5ad71d93cdcd1d879b6d5ed187a36b0002cc34e0ef9883255",
				"transaction": {
					"type": 8,
					"senderPublicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"nonce": "2",
					"fee": "100000000",
					"asset": {
						"recipientId": "18141291412139607230L",
						"amount": "1234567890",
						"data": "random data"
					}
				}
			},
			"output": {
				"type": 8,
				"senderPublicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
				"nonce": "2",
				"fee": "100000000",
				"asset": {
					"recipientId": "18141291412139607230L",
					"amount": "1234567890",
					"data": "random data"
				},
				"signature": "5fd60d57a6dffd631e9933d832e83584067ea52748823f85233c9fe1adedd4e1850195031afba9ef4258ddd5f09adec29d3c5ebf24c6e8e4f04d8e47c4e60e0f",
				"signSignature": "e1ea85377dcf63d1a6bee8f93d01f461bafb1bf8df052efc52c6ebed4610f2691ec16289ee4bef1f5933a19221708c0e60e49836b9793e0fa60d16f3af57440f",
				"id": "4737343361801311741"
			}
		}
	]
}

=== Atomicwallet/lisk-sdk/protocol-specs/generator_outputs/transaction_network_id_and_change_order/transfer_transaction_validate.json
{
	"title": "Valid transfer transaction",
	"summary": "A valid transfer transaction",
	"config": {
		"network": "devnet"
	},
	"runner": "transaction_network_id_and_change_order",
	"handler": "transfer_transaction_validate",
	"testCases": [
		{
			"description": "A valid transfer transaction",
			"input": {
				"account": {
					"passphrase": "wear protect skill sentence lift enter wild sting lottery power floor neglect",
					"privateKey": "j0H/HnXE8PinG65JUiZpKNDpFmD8UTVmrGlP7WEVdJfvrx2XeJfLYNfbnTDo/WaN7gcKwNsfuNGEwGFSqLdfjQ==",
					"publicKey": "768dl3iXy2DX250w6P1mje4HCsDbH7jRhMBhUqi3X40=",
					"address": "j1aFv13LjB07m7yYz/sNDGB3vhc=",
					"nonce": "2"
				},
				"networkIdentifier": "5I/riNtbXPWtcdk83NHYebbV7Rh6NrAALMNODvmIMlU="
			},
			"output": {
				"transaction": "CAgQAhiAwtcvIiDvrx2XeJfLYNfbnTDo/WaN7gcKwNsfuNGEwGFSqLdfjSopCNKF2MwEEhS+BG0zbNDC+95ivEfiAZk5XS7q3BoLcmFuZG9tIGRhdGEyQKDvZW+Nsw/PIJs1CSnmq2pSviYi1fUNkypj9w2CgD1V8vLDUU1ad+i78+0K+7z9tc/Uaq0Z5wXd+3eImoEZtQA="
			}
		}
	]
}
