=== Atomicwallet/lisk-sdk/protocol-specs/schema/lisk_protocol_specs.schema.json
{
	"title": "LiskProtocolSpec",
	"description": "Schema specification for JSON specs output",
	"$id": "https://lisk.io/schemas/protocol_specs",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"additionalProperties": false,
	"required": ["title", "summary", "runner", "handler", "testCases"],
	"properties": {
		"title": {
			"type": "string",
			"description": "A string type value giving a short title of the spec",
			"minLength": 10,
			"maxLength": 100
		},
		"summary": {
			"type": "string",
			"description": "A string type value explaining in detail purpose and value of the spec",
			"minLength": 25,
			"maxLength": 300
		},
		"runner": {
			"type": "string",
			"description": "A string identifier to point to a protocol spec name e.g. dpos, bft",
			"minLength": 3,
			"maxLength": 100,
			"pattern": "[a-z0-9_]*"
		},
		"handler": {
			"type": "string",
			"description": "A string value to differentiate between same identifier for protocol spec",
			"minLength": 3,
			"maxLength": 100,
			"pattern": "[a-z0-9_]*"
		},
		"config": {
			"$ref": "#/definitions/Config"
		},
		"testCases": {
			"type": "array",
			"description": "List down all test cases for current handler and runner",
			"items": {
				"$ref": "#/definitions/TestCase"
			}
		}
	},
	"definitions": {
		"Account": {
			"title": "Account",
			"description": "Schema to specify and validate account in JSON specs",
			"type": "object",
			"properties": {
				"address": {
					"type": "string"
				},
				"publicKey": {
					"type": "string"
				},
				"secondPublicKey": {
					"type": ["string", "null"]
				},
				"username": {
					"type": ["string", "null"]
				},
				"isDelegate": {
					"type": "boolean"
				},
				"secondSignature": {
					"type": "boolean"
				},
				"nameExist": {
					"type": "boolean"
				},
				"balance": {
					"type": ["string", "integer"]
				},
				"multiMin": {
					"type": "integer"
				},
				"multiLifetime": {
					"type": "integer"
				},
				"missedBlocks": {
					"type": "integer"
				},
				"producedBlocks": {
					"type": "integer"
				},
				"rank": {
					"type": ["integer", "null"]
				},
				"fees": {
					"type": "integer"
				},
				"rewards": {
					"type": "integer"
				},
				"vote": {
					"type": ["string", "integer"]
				},
				"productivity": {
					"type": "integer"
				}
			},
			"required": ["address", "publicKey", "isDelegate", "balance"]
		},
		"Block": {
			"title": "Block",
			"description": "Schema to specify and validate blocks in JSON specs",
			"type": "object",
			"properties": {
				"id": {
					"type": "string",
					"format": "id",
					"minLength": 1,
					"maxLength": 20
				},
				"height": {
					"type": "integer"
				},
				"blockSignature": {
					"type": "string",
					"format": "signature"
				},
				"generatorPublicKey": {
					"type": "string",
					"format": "publicKey"
				},
				"numberOfTransactions": {
					"type": "integer"
				},
				"payloadHash": {
					"type": "string",
					"format": "hex"
				},
				"payloadLength": {
					"type": "integer"
				},
				"previousBlockId": {
					"type": "string",
					"format": "id",
					"minLength": 1,
					"maxLength": 20
				},
				"timestamp": {
					"type": "integer"
				},
				"totalAmount": {
					"typeof": "string",
					"format": "amount"
				},
				"totalFee": {
					"typeof": "string",
					"format": "amount"
				},
				"reward": {
					"typeof": "string",
					"format": "amount"
				},
				"transactions": {
					"type": "array",
					"uniqueItems": true
				},
				"version": {
					"type": "integer",
					"minimum": 0
				}
			},
			"required": [
				"blockSignature",
				"generatorPublicKey",
				"numberOfTransactions",
				"payloadHash",
				"payloadLength",
				"timestamp",
				"totalAmount",
				"totalFee",
				"reward",
				"transactions",
				"version"
			]
		},
		"ChainState": {
			"title": "ChainState",
			"description": "A JSON object represents basic chain state for individual spec to be executed.",
			"type": "object",
			"properties": {
				"chain": {
					"type": "array",
					"uniqueItems": true,
					"items": {
						"$ref": "#/definitions/Block"
					}
				},
				"accounts": {
					"type": "array",
					"uniqueItems": true,
					"items": {
						"$ref": "#/definitions/Account"
					}
				}
			}
		},
		"Config": {
			"title": "Config",
			"description": "A JSON object containing all necessary configurations for the environment in which these specs were generated and individual test case can be verified.",
			"type": "object",
			"additionalProperties": true,
			"required": [],
			"properties": {
				"initialState": {
					"$ref": "#/definitions/ChainState"
				}
			}
		},
		"TestCase": {
			"title": "Schema for a single test case",
			"type": "object",
			"additionalProperties": false,
			"required": ["input", "output", "description"],
			"properties": {
				"description": {
					"type": "string",
					"minLength": 10,
					"maxLength": 300
				},
				"config": {
					"description": "Configuration for a single test case",
					"$ref": "#/definitions/Config"
				},
				"input": {
					"type": "object",
					"description": "Input must be specified as a single object. If its complex scenario, it should be divided to multiple to have simple input/output expectations.",
					"minProperties": 1
				},
				"output": {
					"type": "object",
					"description": "Output must be specified as a single object. If its complex scenario, it should be divided to multiple to have simple input/output expectations.",
					"required": [],
					"additionalProperties": true,
					"minProperties": 1,
					"properties": {
						"mutatedState": {
							"description": "Modified chain state",
							"$ref": "#/definitions/ChainState"
						}
					}
				}
			}
		}
	}
}

=== Atomicwallet/lisk-sdk/protocol-specs/generator_outputs/unlock_transaction/unlock_transaction.json
{
	"title": "Valid unlock transaction",
	"summary": "Valid unlock transaction which includes the unlock for the same account",
	"config": {
		"network": "devnet"
	},
	"runner": "unlock_transaction",
	"handler": "unlock_transaction",
	"testCases": [
		{
			"description": "Valid unlock transaction",
			"input": {
				"account": {
					"passphrase": "lava toe nuclear candy erode present guilt develop include type pluck current",
					"publicKey": "jD2BsVVfvkaSrfoQJu4hwENjO5NpkkzyeQ4uD8a0emY=",
					"address": "Z24KgZP2PRUkAslR/oNN9lbG3og="
				},
				"networkIdentifier": "5I/riNtbXPWtcdk83NHYebbV7Rh6NrAALMNODvmIMlU=",
				"delegates": [
					{
						"publicKey": "VDDndVBbMUXBJNFdx8hMp8dR7Lafr2U7+x4MkebiL4o=",
						"address": "d7zFYYWkOnuLRXlHngpuDN8Tvls="
					},
					{
						"publicKey": "c6Vs5AqpkSkyUNm9YUcdGREfAjzxgnyb4Yne7XM/nqI=",
						"address": "4db0eKDEfGuretM2kDcdwBm67t0="
					},
					{
						"publicKey": "iNHU6U8kZv5pdwpRDcjmxjiHW3HpbAK0eRzMAyoqZHI=",
						"address": "VAX+lY+xRy/5jb1G79ePlJncbbU="
					},
					{
						"publicKey": "QVg8cfJmqEIA8L/e6bO7mE9tZ/PJA7pyiMl/Elm/jdw=",
						"address": "/E8iN5x8/RLbzjPYhZEVEQ8Orfs="
					},
					{
						"publicKey": "UVg3ncEQx/wBHPr1JGYBZmiuzGXlv6ecKVjhbaMEkL0=",
						"address": "Mnbi245MZqZJyfj/E3ENQ3xUFNE="
					},
					{
						"publicKey": "fK4fCOSkpDfP/sUJlR7R8wRRQV//clrapGptiUbpV4c=",
						"address": "ErBkLUwRx8pFHmxa6/Gp8padnNo="
					},
					{
						"publicKey": "97nqRDvcGAzUEW4qhuMCY5tLQWWdgY1QEb//BkJFPDo=",
						"address": "14M2a7h/K8l9zKVc5f15BmeoFv4="
					},
					{
						"publicKey": "U+/i4bZuo1o1bgf5nb/XmWXpTnizuACHSF448l/4C3Q=",
						"address": "wr1805a33lSbeJOREog8kMX2Y5E="
					},
					{
						"publicKey": "Qzj4yEF/lvMVaY7GcOjpw1yqCDAYH1VU9hi6iCnUNvA=",
						"address": "zwDhvy0SrGZUvBxjxaW5FbN/ZYk="
					},
					{
						"publicKey": "yoEls6EqL4rUem1RSwDDYHZt9XhdVyA3SPuMYwkgIPo=",
						"address": "pZlDXL6CtdTugvGX16HyPYpJorw="
					},
					{
						"publicKey": "J7fwFhH5WIor9Dd0ubiQztve9pXxuETIFYc/L+zx4p4=",
						"address": "6oa57jHNrn360tJ8vy9RuEphXmc="
					},
					{
						"publicKey": "b/TCt98BMxZha2trZ+0QKJQYSk787jZf0bRZ5NBwzKA=",
						"address": "HoC5Gre50InRBFR/hlOTLUs5Vy0="
					},
					{
						"publicKey": "4fIKixxkGT218An9TYj96b0TILjJIfr+gAus2Uw0eis=",
						"address": "mhC8UDw1gR1EC3uWqt6TRG1RjhY="
					},
					{
						"publicKey": "HrMBMopWgaTToALIkmRO/MBXQ2mF1I1VJhEz2uCvXEE=",
						"address": "f6TNwxSb787pMISHanQQ475sNE8="
					},
					{
						"publicKey": "A1UIXU1swlZcaaJIhG6dHLevAj+NOisxRFoDhqRXWKQ=",
						"address": "33TZBfsTHoSu5kKvs85/EgDF6JA="
					},
					{
						"publicKey": "90DyL/RBN1dFfNJbOQ9TErWxDdCfTtkBhIpXy4S8EmE=",
						"address": "4ltStCMLSSxYDR4JLRKTa+Jxykg="
					},
					{
						"publicKey": "Cb8L1ZPzVPeUnLv0LO39yfq9LX2l/yTg8kxAF+vbdFA=",
						"address": "AskT2dgV3k/YHPwPahSNjo6jDdE="
					},
					{
						"publicKey": "KZiuXGsoOI/WVCYsoZpNZpq/Bnqioo+i7LlAedE4bsk=",
						"address": "0Smk0KZr1J7kRvpxHk2oU/UtoIU="
					},
					{
						"publicKey": "+LKC/na+0R4ASPZo4naPG1NGrNd7Ov4qAcmzh0YS+6I=",
						"address": "R0dZtNKK64tS9pxRO4xcV3YF5E0="
					},
					{
						"publicKey": "GVKMQfdJ+wrNhAtTSYI6/qjZbZOAz0xnSlz1IkF6aUY=",
						"address": "RETTPY2Wo9EelimD9bNsgdn6RSg="
					}
				]
			},
			"output": {
				"transaction": "CA4QAxiA3qDLBSIgjD2BsVVfvkaSrfoQJu4hwENjO5NpkkzyeQ4uD8a0emYqkgUCHgoUd7zFYYWkOnuLRXlHngpuDN8TvlsQgJTr3AMYIAIfChTh1vR4oMR8a6t60zaQNx3AGbru3RCA6O2hugEYDAIfChRUBf6Vj7FHL/mNvUbv14+UmdxttRCAgPKLqAkYDgIfChR3vMVhhaQ6e4tFeUeeCm4M3xO+WxCA0M3PnAwYEwIfChR3vMVhhaQ6e4tFeUeeCm4M3xO+WxCAoKmTkQ8YMgIfChRUBf6Vj7FHL/mNvUbv14+UmdxttRCA8ITXhRIYDgIfChRUBf6Vj7FHL/mNvUbv14+UmdxttRCA8ITXhRIYDgIfChT8TyI3nHz9EtvOM9iFkRURDw6t+xCA4Jei4xoYIQIfChQyduLbjkxmpknJ+P8TcQ1DfFQU0RCA8JnFiQQYEwIfChQSsGQtTBHHykUebFrr8anylp2c2hCAqOqk5AMYNQIeChTXgzZruH8ryX3MpVzl/XkGZ6gW/hCAlOvcAxggAh8KFMK9fNOWt95Um3iTkRKIPJDF9mOREIDo7aG6ARgSAh8KFM8A4b8tEqxmVLwcY8WluRWzf2WJEICA8ouoCRgdAh8KFKWZQ1y+grXU7oLxl9eh8j2KSaK8EIDQzc+cDBgGAh8KFGduCoGT9j0VJALJUf6DTfZWxt6IEICgqZORDxgsAh8KFB6AuRq3udCJ0QRUf4ZTky1LOVctEIDwhNeFEhgpAh8KFJoQvFA8NYEdRAt7lqrek0RtUY4WEICQvN7uFxgNAh8KFH+kzcMUm+/O6TCEh2p0EOO+bDRPEIDgl6LjGhgZAh8KFN902QX7Ex6EruZCr7POfxIAxeiQEIDwmcWJBBgfAh8KFOJbUrQjC0ksWA0eCS0Sk2viccpIEICo6qTkAxgVMkDhiMWcCL4FmjtJ86+rbVSUDXg+vUwKEUei2+Stn6Apa4AY3HPk0JSSI2y6ud3hzt6dTwOzm4VxwLP7nzTsHdUA"
			}
		}
	]
}

=== Atomicwallet/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/validBytesEncodings.json
{
	"title": "Valid bytes encodings",
	"summary": "Examples of encoding bytes as required by lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "validBytesEncodings",
	"testCases": [
		{
			"description": "Encoding of bytes types",
			"config": {
				"network": "devnet"
			},
			"input": {
				"bytes": {
					"object": {
						"address": "e11a11364738225813f86ea85214400e5db08d6e"
					},
					"schema": {
						"type": "object",
						"properties": {
							"address": {
								"dataType": "bytes",
								"fieldNumber": 1
							}
						}
					}
				},
				"emptyBytes": {
					"object": {
						"address": {
							"type": "Buffer",
							"data": []
						}
					},
					"schema": {
						"type": "object",
						"properties": {
							"data": {
								"dataType": "string",
								"fieldNumber": 1
							}
						}
					}
				}
			},
			"output": {
				"bytes": "0a14e11a11364738225813f86ea85214400e5db08d6e",
				"emptyBytes": "0a00"
			}
		}
	]
}

=== Atomicwallet/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/validStringEncodings.json
{
	"title": "Valid string encodings",
	"summary": "Examples of encoding strings as required by lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "validStringEncodings",
	"testCases": [
		{
			"description": "Encoding of boolean types",
			"config": {
				"network": "devnet"
			},
			"input": {
				"string": {
					"object": {
						"data": "Checkout Lisk SDK!"
					},
					"schema": {
						"type": "object",
						"properties": {
							"data": {
								"dataType": "string",
								"fieldNumber": 1
							}
						}
					}
				},
				"emptyString": {
					"object": {
						"data": ""
					},
					"schema": {
						"type": "object",
						"properties": {
							"data": {
								"dataType": "string",
								"fieldNumber": 1
							}
						}
					}
				}
			},
			"output": {
				"string": "0a12436865636b6f7574204c69736b2053444b21",
				"emptyString": "0a00"
			}
		}
	]
}

=== Atomicwallet/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/validObjectEncodings.json
{
	"title": "Valid object encodings",
	"summary": "Examples of encoding objects as required by lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "validObjectEncodings",
	"testCases": [
		{
			"description": "Encoding of object types",
			"config": {
				"network": "devnet"
			},
			"input": {
				"object": {
					"object": {
						"address": "e11a11364738225813f86ea85214400e5db08d6e",
						"balance": 10000000,
						"isDelegate": true,
						"name": "delegate",
						"asset": {
							"data": "Check out the Lisk SDK now in binary!"
						}
					},
					"schema": {
						"type": "object",
						"properties": {
							"address": {
								"dataType": "bytes",
								"fieldNumber": 1
							},
							"balance": {
								"dataType": "uint64",
								"fieldNumber": 2
							},
							"isDelegate": {
								"dataType": "boolean",
								"fieldNumber": 3
							},
							"name": {
								"dataType": "string",
								"fieldNumber": 4
							},
							"asset": {
								"type": "object",
								"fieldNumber": 5,
								"properties": {
									"data": {
										"dataType": "string",
										"fieldNumber": 1
									}
								}
							}
						}
					}
				},
				"objectWithOptionalProp": {
					"object": {
						"isActive": true,
						"value": 1
					},
					"schema": {
						"type": "object",
						"properties": {
							"isActive": {
								"dataType": "boolean",
								"fieldNumber": 1
							},
							"balance": {
								"data": "bytes",
								"fieldNumber": 2
							},
							"value": {
								"dataType": "uint64",
								"fieldNumber": 3
							}
						}
					}
				}
			},
			"output": {
				"object": "0a14e11a11364738225813f86ea85214400e5db08d6e1080ade2041801220864656c65676174652a270a25436865636b206f757420746865204c69736b2053444b206e6f7720696e2062696e61727921",
				"objectWithOptionalProp": "08011801"
			}
		}
	]
}

=== Atomicwallet/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/validArrayEncodings.json
{
	"title": "Valid array encodings",
	"summary": "Examples of encoding arrays as required by lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "validArrayEncodings",
	"testCases": [
		{
			"description": "Encoding of array types",
			"config": {
				"network": "devnet"
			},
			"input": {
				"ArrayOfIntegers": {
					"object": {
						"list": [3, 1, 4, 1, 5, 9, 2, 6, 5]
					},
					"schema": {
						"type": "object",
						"properties": {
							"list": {
								"type": "array",
								"items": {
									"dataType": "uint32"
								},
								"fieldNumber": 1
							}
						}
					}
				},
				"arrayBools": {
					"object": {
						"list": [true, true, false, true, false, false]
					},
					"schema": {
						"type": "object",
						"properties": {
							"list": {
								"type": "array",
								"items": {
									"dataType": "bool"
								},
								"fieldNumber": 1
							}
						}
					}
				},
				"arrayStrings": {
					"object": {
						"list": ["lisk", "", "gogogog"]
					},
					"schema": {
						"type": "object",
						"properties": {
							"list": {
								"type": "array",
								"items": {
									"dataType": "string"
								},
								"fieldNumber": 1
							}
						}
					}
				},
				"arrayOfObjects": {
					"object": {
						"myArray": [
							{
								"address": "e11a11364738225813f86ea85214400e5db08d6e",
								"amount": 100000
							},
							{
								"address": "aa2a11364738225813f86ea85214400e5db08fff",
								"amount": 300000
							}
						]
					},
					"schema": {
						"schema": {
							"type": "object",
							"properties": {
								"list": {
									"type": "array",
									"fieldNumber": 1,
									"items": {
										"type": "object",
										"properties": {
											"address": {
												"dataType": "string",
												"fieldNumber": 1
											},
											"amount": {
												"dataType": "uint64",
												"fieldNumber": 2
											}
										}
									}
								}
							}
						}
					}
				},
				"emptyArray": {
					"object": {
						"list": []
					},
					"schema": {
						"type": "object",
						"properties": {
							"list": {
								"type": "array",
								"items": {
									"dataType": "uint32"
								},
								"fieldNumber": 1
							}
						}
					}
				}
			},
			"output": {
				"arrayOfIntegersEncoded": "0a09030104010509020605",
				"arrayBoolsEncoded": "0a06010100010000",
				"arrayStringsEncoded": "0a046c69736b0a000a07676f676f676f67",
				"arrayOfObjectsEncoded": "0a2e0a286531316131313336343733383232353831336638366561383532313434303065356462303864366510a08d060a2e0a286161326131313336343733383232353831336638366561383532313434303065356462303866666610e0a712",
				"emptyArrayEncoded": ""
			}
		}
	]
}

=== Atomicwallet/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/string_encodings.json
{
	"title": "Encondings for string types supported by lisk-codec",
	"summary": "Examples of encoding strings with lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "string_encodings",
	"testCases": [
		{
			"description": "Encoding of string",
			"input": {
				"object": {
					"data": "Checkout Lisk SDK!"
				},
				"schema": {
					"$id": "object7",
					"type": "object",
					"properties": {
						"data": {
							"dataType": "string",
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "0a12436865636b6f7574204c69736b2053444b21"
			}
		},
		{
			"description": "Encoding of empty string",
			"input": {
				"object": {
					"data": ""
				},
				"schema": {
					"$id": "object8",
					"type": "object",
					"properties": {
						"data": {
							"dataType": "string",
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "0a00"
			}
		}
	]
}

=== Atomicwallet/lisk-sdk/protocol-specs/generator_outputs/transaction_network_id_and_change_order/transfer_transaction_with_multi_signature_validate.json
{
	"title": "Valid transfer transaction with multi signature",
	"summary": "A valid transfer transaction with multi signature",
	"config": {
		"network": "devnet"
	},
	"runner": "transaction_network_id_and_change_order",
	"handler": "transfer_transaction_with_multi_signature_validate",
	"testCases": [
		{
			"description": "A valid transfer transaction with multi signature",
			"input": {
				"account": {
					"passphrase": "wear protect skill sentence lift enter wild sting lottery power floor neglect",
					"privateKey": "8f41ff1e75c4f0f8a71bae4952266928d0e91660fc513566ac694fed61157497efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"publicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"address": "2129300327344985743L",
					"nonce": "2"
				},
				"coSigners": [
					{
						"passphrase": "better across runway mansion jar route valid crack panic favorite smooth sword",
						"privateKey": "de1520f8589408e76a97643ba7d27f20009b06899816c8af20f9b03f4a4bd8a66766ce280eb99e45d2cc7d9c8c852720940dab5d69f480e80477a97b4255d5d8",
						"publicKey": "6766ce280eb99e45d2cc7d9c8c852720940dab5d69f480e80477a97b4255d5d8",
						"address": "13191770412077040757L",
						"nonce": "2"
					},
					{
						"passphrase": "mirror swap middle hunt angle furnace maid scheme amazing box bachelor debris",
						"privateKey": "ad7462eb8f682b0c3424213ead044381ba0007bb65ce26287fc308027c871d951387d8ec6306807ffd6fe27ea3443985765c1157928bb09904307956f46a9972",
						"publicKey": "1387d8ec6306807ffd6fe27ea3443985765c1157928bb09904307956f46a9972",
						"address": "2443122499609067441L",
						"nonce": "2"
					}
				],
				"networkIdentifier": "e48feb88db5b5cf5ad71d93cdcd1d879b6d5ed187a36b0002cc34e0ef9883255",
				"transaction": {
					"type": 8,
					"senderPublicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"nonce": "2",
					"fee": "100000000",
					"asset": {
						"recipientId": "18141291412139607230L",
						"amount": "1234567890",
						"data": "random data"
					}
				}
			},
			"output": {
				"type": 8,
				"senderPublicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
				"nonce": "2",
				"fee": "100000000",
				"asset": {
					"recipientId": "18141291412139607230L",
					"amount": "1234567890",
					"data": "random data"
				},
				"signature": "e98d7ec13909c2d8d58c4bafdf723b6f88480619b237c58dc96c9ae6cad7e74f8b8cfe72f0137827b17c0ba1def07f6fa92af22872a23060bbdae6651bb98807",
				"signatures": [
					"c9c01590063c037edc356b9506db81adbbd2026e29e714d257ee8f8ebc2c6c8c08c7228c83d4a59a42c7364d519c10de31e20b6c393be15b33e2a1f67cd10009",
					"6810d1113a528927dbbbf78e427d675e9ed1c8e5008aa75877bc8aa2a2257cdff977ac938c5210ac0d4506138c46cedeeeee8b0ec96411352131a0cdd8e03406"
				],
				"id": "14028804809042236201"
			}
		}
	]
}

=== Atomicwallet/lisk-sdk/protocol-specs/generator_outputs/transaction_network_id_and_change_order/delegate_transaction_validate.json
{
	"title": "Valid delegate transaction",
	"summary": "A valid delegate transaction",
	"config": {
		"network": "devnet"
	},
	"runner": "transaction_network_id_and_change_order",
	"handler": "delegate_transaction_validate",
	"testCases": [
		{
			"description": "A valid delegate transaction",
			"input": {
				"account": {
					"passphrase": "wear protect skill sentence lift enter wild sting lottery power floor neglect",
					"privateKey": "8f41ff1e75c4f0f8a71bae4952266928d0e91660fc513566ac694fed61157497efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"publicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"address": "2129300327344985743L",
					"nonce": "2"
				},
				"networkIdentifier": "e48feb88db5b5cf5ad71d93cdcd1d879b6d5ed187a36b0002cc34e0ef9883255",
				"transaction": {
					"type": 10,
					"senderPublicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"nonce": "2",
					"fee": "100000000",
					"asset": {
						"username": "new_delegate"
					}
				}
			},
			"output": {
				"type": 10,
				"senderPublicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
				"nonce": "2",
				"fee": "100000000",
				"asset": {
					"username": "new_delegate"
				},
				"signature": "eeaee4c7abec51ac6b8f406c281ca073d99bb455dbc8f5ccbc137b34ccb92e372cd93f2256e8978d0962efea6def770f7ae65d2616ac1071fd3488a8e0f1b301",
				"id": "18179433578411384385"
			}
		}
	]
}
